### ISSUE TITLE
Build problem on Fedora 38

### ISSUE THREAD

**Issue by ycollet** [sjoerdvankreel/infernal-synth#12]
During the build on Fedora 38, a problem occured during Presets copy.
The copy operated in cmake failed because of a wrong filename.

cmake tries to copy from presets/FX to the build directory while only a presets/Fx directory exists (Linux is case sensitive for filenames)

**Comment by sjoerdvankreel** [comment]
Hey! I had long given up on linux support for infernal. It was not written with linux in mind. It was part of the reason why i started firefly-synth which I hope has much better cross-platform support. Even if i was to fix small build problems like this for infernal, the resulting binaries will not be usable. They have many gui-related issues on linux.

**Comment by ycollet** [comment]
Yes, you're right. InfernalSynth builds but when I load the plugin, no GUI.
I
