### ISSUE TITLE
FL Studio 21 b3517 refuses to use the plugin as "synth"

### ISSUE THREAD

**Issue by Vospi** [sjoerdvankreel/infernal-synth#6]
FL Studio 21 b3517 refuses to use the plugin as "synth" and insists on it being an "effect".

**Details:** both vst3s provided with the release are recognized as "effects" even if I specifically set them to be "synths", so, instruments in FL terminology. So, when I open it, I see an error window: You tried to open an effect plugin into a channel. Open the plugin InfernalSynth1.2 in the mixer instead. I don't see the UI at all and basically can't participate in the OSC. And the plugin looks really, really detailed and intriguing, so I want to! :)

Tech specs:
Windows 10 x64, FL Studio 21 b3517 (latest legit version that is not beta).

(Thanks for such a massive product, can't wait to try it for actual music writing)

**Comment by sjoerdvankreel** [comment]
Hey, thanks for reporting. I've seen the same issue on other hosts but I completely forgot.
The right way to fix this is probably to provide separate dlls for fx/instrument but that's gonna take some time.
So, as to not hinder the OSC, i uploaded an instrument-only version to here https://sjoerdvankreel.github.io/infernal-synth/. 
Could you check and see if it works for you? If so, i'll drop a mention at the OSC forum, too.

**Comment by sjoerdvankreel** [comment]
Fixed in 1.3.
