### ISSUE TITLE
Cubase: PresetName Keyboard Focus 

### ISSUE THREAD

**Issue by audio-dsp-de** [sjoerdvankreel/infernal-synth#7]
If I try to save a preset, the keyboard focus is on Cubase. Only keys not assigned to cubase are recognized. So my presets are saved as qqq.vstpreset.

Workaround: Save and rename in Explorer

**Comment by sjoerdvankreel** [comment]
Thanks for reporting. Will download cubase and hope to get it fixed before my trial period runs out ;)

**Comment by sjoerdvankreel** [comment]
Just writing down some relevant stuff before i forget what's going on.

* This is not specific to cubase, reaper has the same problem f.e. with spacebar
* Also not specific to save preset, exact-edit field suffers the same problem
* Some hosts steal key input even if a juce text editor has focus. Not a problem in infernal 1.1 (vstgui)
* Might be fixed using addToDesktop() for the save dialog. Not sure if thats the way to go for exact-edit.

There's a long history of problems with this:
* https://forum.juce.com/t/keyboard-focus-and-plugins/33870
* https://forum.juce.com/t/reaper-stealing-spacebar-keystrokes-in-texteditor/30689
* https://forum.juce.com/t/vst-plugin-still-not-getting-keystrokes/6582

**Comment by sjoerdvankreel** [comment]
Just found out both reaper and fl studio have options to not intercept keys and send them directly to the focused plugin.
Do you by any chance know if cubase can do the same?

**Comment by audio-dsp-de** [comment]
There is no option like that in Cubase AFAIK (and I looked for it in all prefrences). I am not sure what causes the problem. I use JUCE combobox for changing preset names and it gets the keyboard focus if clicked. Your save dialog seems to work differently. I hope you find a solution. Perhaps it has something to do, if the dialog is modal or not.

**Comment by sjoerdvankreel** [comment]
At first i thought maybe combobox and textbox behave differently, but, i tried "factory preset" again in cubase, and cubase still steals keyboard focus. However juce's addToDesktop() fixes that for save/load dialogs. It does have the side effect that the dialog window becomes top-level and is added to the windows taskbar, but thats probably the exact same reason that allows keypresses to come through.

![image](https://github.com/sjoerdvankreel/infernal-synth/assets/2647549/56d5836b-36c8-4876-9c9f-be8326d24f7c)

That leaves me with the exact-edit field (above theme selector) but i'd rather play it safe and show a modal dialog for exact-editing upon right-clicking any of the knobs. What do you think?

**Comment by sjoerdvankreel** [comment]
Fixed in 1.3. You may have to clear/rescan plugin cache.
