### ISSUE TITLE
Save some global parameter

### ISSUE THREAD

**Issue by audio-dsp-de** [sjoerdvankreel/infernal-synth#9]
Is it possible that the 

directory where I last saved a preset
UI Size
UI Style 

is kept, when a new instance of the plugin is loaded. At the moment the default is set every time I reload the plugin

DAW: Cubase

**Comment by sjoerdvankreel** [comment]
That's actually something i wanted to do for quite some time, just havent got around to it. But fully agree, all the clicking back and forth is annoying as hell. I'd have to create some global preferences file somewhere outside the plugin/vstpreset. Not trivial but definately doable. Put on the to-do list.

**Comment by sjoerdvankreel** [comment]
Fixed in 1.3. You may have to clear/rescan plugin cache.
